name: Build and Push Multi-Platform Docker Image to GHCR

on:
  push:
    branches:
      - main
      - gorm
      - '*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.1  # Renovate can track and update this

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0  # Pin to version for Renovate

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.1.0  # Pin for Renovate compatibility
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image tags
        id: vars
        run: |
          REPO_LOWERCASE=${GITHUB_REPOSITORY,,}
          IMAGE_NAME=ghcr.io/$REPO_LOWERCASE
          COMMIT_TAG=${GITHUB_SHA::7}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          # Sanitize branch name for Docker tag (replace / with -)
          BRANCH_TAG=${BRANCH_NAME//\//-}

          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "commit_tag=$COMMIT_TAG" >> $GITHUB_OUTPUT
          echo "branch_tag=$BRANCH_TAG" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (multi-platform)
        uses: docker/build-push-action@v5.3.0  # Renovate-friendly
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.branch_tag }}
            ${{ steps.vars.outputs.image_name }}:sha-${{ steps.vars.outputs.commit_tag }}
            ${{ steps.vars.outputs.branch_name == 'main' && format('{0}:latest', steps.vars.outputs.image_name) || '' }}
